---
deployment:
  tasks:
    - export REPOPATH = /home/myworksite/repositories/science-pr/*
    - export SITEPATH = /home/myworksite/public_html/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH